repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt (gofumpt)
        entry: bash
        args: [-c, 'cd backend && go run mvdan.cc/gofumpt@latest -w .']
        language: system
        files: \.go$

      - id: go-imports
        name: go imports
        entry: bash
        args: [-c, 'cd backend && go run golang.org/x/tools/cmd/goimports@latest -w -local "g_gen" .']
        language: system
        files: \.go$

      - id: go-vet
        name: go vet
        entry: bash
        args: [-c, 'cd backend && go vet ./...']
        language: system
        files: \.go$
        pass_filenames: false

      - id: staticcheck
        name: staticcheck
        entry: bash
        args: [-c, 'cd backend && go run honnef.co/go/tools/cmd/staticcheck@latest ./...']
        language: system
        files: \.go$
        pass_filenames: false

      - id: golangci-lint
        name: golangci-lint
        entry: bash
        args: [-c, 'cd backend && go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run --fix ./...']
        language: system
        files: \.go$
        pass_filenames: false

      - id: go-test
        name: go test
        entry: bash
        args: [-c, 'cd backend && go test ./...']
        language: system
        files: \.go$
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
