// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q            = new(Query)
	Municipality *municipality
	Prefecture   *prefecture
	WorkCategory *workCategory
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Municipality = &Q.Municipality
	Prefecture = &Q.Prefecture
	WorkCategory = &Q.WorkCategory
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		Municipality: newMunicipality(db, opts...),
		Prefecture:   newPrefecture(db, opts...),
		WorkCategory: newWorkCategory(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Municipality municipality
	Prefecture   prefecture
	WorkCategory workCategory
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Municipality: q.Municipality.clone(db),
		Prefecture:   q.Prefecture.clone(db),
		WorkCategory: q.WorkCategory.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Municipality: q.Municipality.replaceDB(db),
		Prefecture:   q.Prefecture.replaceDB(db),
		WorkCategory: q.WorkCategory.replaceDB(db),
	}
}

type queryCtx struct {
	Municipality IMunicipalityDo
	Prefecture   IPrefectureDo
	WorkCategory IWorkCategoryDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Municipality: q.Municipality.WithContext(ctx),
		Prefecture:   q.Prefecture.WithContext(ctx),
		WorkCategory: q.WorkCategory.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
