// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMunicipality = "municipalities"

// Municipality mapped from table <municipalities>
type Municipality struct {
	ID                    int32      `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:内部ID（主キー、自動採番）" json:"id"`                                                                                                                                            // 内部ID（主キー、自動採番）
	PrefectureCode        string     `gorm:"column:prefecture_code;type:character varying(2);not null;index:idx_municipalities_prefecture_id,priority:1;comment:都道府県ID（外部キー、都道府県マスタのID）" json:"prefecture_code"`                                                               // 都道府県ID（外部キー、都道府県マスタのID）
	OrganizationCode      string     `gorm:"column:organization_code;type:character varying(6);not null;index:idx_municipalities_organization_code,priority:1;comment:団体コード（総務省地方公共団体コード、6桁）" json:"organization_code"`                                                        // 団体コード（総務省地方公共団体コード、6桁）
	PrefectureNameKanji   string     `gorm:"column:prefecture_name_kanji;type:character varying(10);not null;index:idx_municipalities_pref_muni_kanji,priority:2;index:idx_municipalities_prefecture_kanji,priority:1;comment:都道府県名（漢字表記）" json:"prefecture_name_kanji"`       // 都道府県名（漢字表記）
	MunicipalityNameKanji string     `gorm:"column:municipality_name_kanji;type:character varying(50);not null;index:idx_municipalities_municipality_kanji,priority:1;index:idx_municipalities_pref_muni_kanji,priority:1;comment:市区町村名（漢字表記）" json:"municipality_name_kanji"` // 市区町村名（漢字表記）
	PrefectureNameKana    string     `gorm:"column:prefecture_name_kana;type:character varying(20);not null;index:idx_municipalities_prefecture_kana,priority:1;comment:都道府県名（カタカナ表記）" json:"prefecture_name_kana"`                                                            // 都道府県名（カタカナ表記）
	MunicipalityNameKana  string     `gorm:"column:municipality_name_kana;type:character varying(100);not null;index:idx_municipalities_municipality_kana,priority:1;comment:市区町村名（カタカナ表記）" json:"municipality_name_kana"`                                                     // 市区町村名（カタカナ表記）
	IsActive              bool       `gorm:"column:is_active;type:boolean;not null;index:idx_municipalities_is_active,priority:1;default:true;comment:有効フラグ（TRUE: 有効、FALSE: 無効）" json:"is_active"`                                                                             // 有効フラグ（TRUE: 有効、FALSE: 無効）
	Prefecture            Prefecture `gorm:"foreignKey:PrefectureCode;references:Code" json:"prefecture"`
}

// TableName Municipality's table name
func (*Municipality) TableName() string {
	return TableNameMunicipality
}
