// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWorkCategory = "work_categories"

// WorkCategory mapped from table <work_categories>
type WorkCategory struct {
	ID           int32  `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:工種区分ID（主キー、自動掲番）" json:"id"`                                                               // 工種区分ID（主キー、自動掲番）
	CategoryName string `gorm:"column:category_name;type:character varying(20);not null;index:idx_work_categories_category_name,priority:1;comment:工種区分名（漢字表記）" json:"category_name"`  // 工種区分名（漢字表記）
	IconName     string `gorm:"column:icon_name;type:character varying(50);not null;index:idx_work_categories_icon_name,priority:1;comment:アイコンファイル名" json:"icon_name"`                // アイコンファイル名
	SortOrder    int32  `gorm:"column:sort_order;type:integer;not null;index:idx_work_categories_sort_order,priority:1;comment:表示順序" json:"sort_order"`                                // 表示順序
	IsActive     bool   `gorm:"column:is_active;type:boolean;not null;index:idx_work_categories_is_active,priority:1;default:true;comment:有効フラグ（TRUE: 有効、FALSE: 無効）" json:"is_active"` // 有効フラグ（TRUE: 有効、FALSE: 無効）
}

// TableName WorkCategory's table name
func (*WorkCategory) TableName() string {
	return TableNameWorkCategory
}
